// Problem 0002
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
// starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
// the sum of the even-valued terms.

#include <cstdint>
#include <iostream>

int main() {
    constexpr uint32_t LIMIT = 4'000'000U;
    uint32_t           fib1 = 3U, fib2 = 5U, sum = 2U;
    while (fib2 < LIMIT) {
        fib2 += fib1;
        fib1 = fib2 - fib1;
        if (fib2 % 2U == 0U) {
            sum += fib2;
        }
    }
    std::cout << sum << '\n';
    return 0;
}
